# ---------------------------------------------
# MLSG Palworld Dockerfile
# ---------------------------------------------
FROM        ghcr.io/parkervcp/steamcmd:proton

LABEL       author="Ken Ren" maintainer="ken.ren98@gmail.com"
            
# 设置用户和工作目录
RUN         useradd -m -d /home/container -s /bin/bash container
USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

STOPSIGNAL  SIGINT

# 导入必要的文件和脚本
COPY        --chown=container:container 03-Palworld/entrypoint.sh /entrypoint.sh
COPY        --chown=container:container 03-Palworld/pal_auto_mods.sh    /usr/local/bin/
COPY        --chown=container:container 00-Tools/7zz               /usr/local/bin/
RUN chmod +x /usr/local/bin/pal_auto_mods.sh \
    && chmod +x /usr/local/bin/7zz \
    && chmod +x /entrypoint.sh
ENTRYPOINT  ["/usr/bin/tini", "-g", "--"]
CMD         ["/entrypoint.sh"]