name: MLSG DST Image Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - '02-DST/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download DST-Shell from EGGs repo
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
               -H "Accept: application/vnd.github.raw" \
               -o "./02-DST/dst_auto_mods.sh" \
               "https://api.github.com/repos/Mr-Leaves-Server-Group/Eggs/contents/02-DST/dst_auto_mods.sh?ref=main"

          chmod +x "./02-DST/dst_auto_mods.sh"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./02-DST/Dockerfile
          push: true
          tags: kenren98/mlsg:dst